// <auto-generated />
namespace Blog_Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Relationship_UserUserCredentials : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Relationship_UserUserCredentials));
        
        string IMigrationMetadata.Id
        {
            get { return "201608021231335_Relationship_User-UserCredentials"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
