// <auto-generated />
namespace Blog_Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tables_for_blogDB_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tables_for_blogDB_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201606231316365_tables_for_blogDB_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
