// <auto-generated />
namespace Blog_Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeRelationshipUser_UserCredentials : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeRelationshipUser_UserCredentials));
        
        string IMigrationMetadata.Id
        {
            get { return "201608021303060_removeRelationship-User_UserCredentials"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
