// <auto-generated />
namespace Blog_Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class relationship_WritesTopics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relationship_WritesTopics));
        
        string IMigrationMetadata.Id
        {
            get { return "201606231403345_relationship_Writes-Topics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
