// <auto-generated />
namespace Blog_Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addNewColumnToThe_Userstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNewColumnToThe_Userstable));
        
        string IMigrationMetadata.Id
        {
            get { return "201608021312577_addNewColumnToThe_Users-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
